name: Deploy Nginx

on:
  push:
    branches:
      - master
    paths:
      - '3-ci_cd/nginx/index.html' #~ Solo se ejecutar치 si se modifica el archivo index.html
  pull_request:
    branches:
      - master
    paths:
      - '3-ci_cd/nginx/index.html' #~ Solo se ejecutar치 si se modifica el archivo index.html
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #~ Realiza un checkout del repositorio (clona el repositorio en la m치quina virtual)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 #~ Setea Docker Buildx para construir im치genes multiplataforma

      - name: Login to Docker Hub
        uses: docker/login-action@v2 #~ Se loguea en Docker Hub para poder subir la imagen
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} #~ Se crea un token en Docker Hub y se guarda en los secrets del repositorio

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 #~ Construye y sube la imagen a Docker Hub
        with:
          context: ./3-ci_cd/nginx
          file: ./3-ci_cd/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest
      
      - name: Deploy to Docker Compose
        run: |
          cd ./3-ci_cd/
          docker-compose down
          docker-compose up -d 