name: Deploy Nginx

on:
  push:
    branches:
      - master
    paths:
      - '3-ci_cd/nginx/index.html'
  pull_request:
    branches:
      - master
    paths:
      - '3-ci_cd/nginx/index.html'
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #~ Check out your repository so your workflow can access it

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 #~ Set up Docker Buildx to build multi-platform images

      - name: Login to Docker Hub
        uses: docker/login-action@v2 #~ Log in to Docker Hub so you can push images to it
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2 #~ Build and push Docker images to a container registry
        with:
          context: ./3-ci_cd/nginx
          file: ./3-ci_cd/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-nginx:latest
      
      - name: Deploy to Docker Compose
        run: |
          cd ./3-ci_cd/
          docker-compose down
          docker-compose up -d